I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 147, in script call
    call simOuNao
  File "game/script.rpy", line 194, in script
    $genericBool = true
  File "game/script.rpy", line 194, in <module>
    $genericBool = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 147, in script call
    call simOuNao
  File "game/script.rpy", line 194, in script
    $genericBool = true
  File "C:\Users\Vic\Desktop\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Vic\Desktop\renpy\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 194, in <module>
    $genericBool = true
NameError: name 'true' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Ex Fumante: A Jornada 1.0
Tue Dec 27 21:50:39 2022
